apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: managed-cluster
  region: us-east-1
managedNodeGroups:
  - name: nodos1
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    volumeSize: 20
    labels: {project: web}
    tags:
      project: web
