apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-mount
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    volumeMounts:
    - name: secrets
      mountPath: "/etc/secrets"
      readOnly: true
  volumes:
  - name: secrets
    secret:
      secretName: credenciales-mainfest
