apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-mount-item-env-var
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: credenciales-mainfest
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: credenciales-mainfest
            key: password
