
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-testing-extname
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      environment: testing-extname
  template:
    metadata:
      labels: 
        app: nginx
        environment: testing-extname
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
     
